[package]
name = "user-stat"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
chrono = {workspace = true }

[dev-dependencies]
anyhow={workspace = true}
fake = { version = "4.2.0", features = ["derive", "chrono"] }
nanoid = "0.4.0"
rand = "0.9.0"
serde = {workspace = true }
sqlx = {workspace = true }
tokio = { workspace = true }
